export const PatientStyles = {
    relative: { position: 'relative' },
    patientHeader: { margin: '8px 0 18px' },
    hospitalName: { color: '#2563eb' },
    headerPadImage: { marginLeft: '20px' },
    tabsContainer: { display: 'flex', justifyContent: 'center', gap: 0, margin: '18px 0' },
    tabButton: { padding: '8px 14px', borderRadius: 0, cursor: 'pointer', display: 'inline-block' },
    activeTab: { border: 'none', background: '#0a66ff', color: '#fff', boxShadow: '0 2px 6px rgba(10,102,255,0.15)' },
    inactiveTab: { border: '1px solid #dfe7ff', background: '#fff', color: '#333', boxShadow: 'none' },
    profileSectionContainer: { display: 'flex', justifyContent: 'center', paddingTop: 6 },
    profileCard: { position: 'relative', width: 760, background: '#fff', borderRadius: 8, boxShadow: '0 6px 18px rgba(11,45,90,0.06)', padding: 22, border: '1px solid rgba(10,102,255,0.06)' },
    pdfBtn: { right: 12, top: 12, border: 'none', background: '#0a66ff', color: '#fff', padding: '6px 8px', borderRadius: 4, cursor: 'pointer', boxShadow: '0 2px 6px rgba(10,102,255,0.15)' },
    profileCardHeader: { display: 'flex', alignItems: 'center', gap: 20 },
    profileAvatarWrapper: { flex: '0 0 96px', display: 'flex', justifyContent: 'flex-start', alignItems: 'flex-start' },
    profileAvatar: { width: 96, height: 96, borderRadius: '50%', marginBottom: '100px', border: '4px solid #f3f7ff' },
    flex1: { flex: 1 },
    profileNameContainer: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
    patientName: { margin: 0, fontSize: 22, color: '#111', fontWeight: 700 },
    patientSubDetail: { color: '#7a869a', marginTop: 6, fontSize: 14 },
    marginTop8: { marginTop: 8 },
    patientCode: { color: '#0a66ff', fontWeight: 700, fontSize: 13, textDecoration: 'none' },
    profileHeaderActions: { flex: '0 0 120px', textAlign: 'right' },
    divider: { border: 'none', borderTop: '2px solid #000000', margin: '16px 0' },
    contactDetails: { display: 'flex', gap: 30, color: '#444', fontSize: 14 },
    contactItem: { marginBottom: 8, fontWeight: 400 },
    inputSmall: { width: 60 },
    inputExtraSmall: { width: 40 },
    vitalsSummaryContainer: { display: 'flex', justifyContent: 'center', margin: '24px 0' },
    vitalsSummaryWrapper: { display: 'flex', gap: 24, flexWrap: 'wrap', width: '100%', maxWidth: 1600 },
    vitalsSummaryCard: { border: '1px solid #e0e0e0', borderRadius: 8, background: '#fff', boxShadow: '0 2px 8px rgba(0,0,0,0.04)', padding: '16px 24px 24px 24px', minWidth: 320, flex: '1 1 320px', maxWidth: 600 },
    vitalsSummaryHeader: { justifyContent: 'space-between', marginBottom: 8 },
    vitalsSummaryTitle: { color: '#1976d2', fontWeight: 600, fontSize: 16 },
    vitalsSummaryContent: { display: 'flex', justifyContent: 'space-between', gap: 24 },
    vitalItem: { marginBottom: 8, color: '#333', marginTop: 16 },
    vitalValue: { color: '#1976d2' },
    vitalValueBold: { color: '#1976d2', fontWeight: 600 },
    sectionTitle: { marginTop: 0, marginBottom: 20 },
    historyTable: { width: '100%', borderCollapse: 'collapse', marginBottom: 20, border: '1px solid #e0e0e0' },
    tableHeader: { background: '#f5f5f5', borderBottom: '2px solid #ddd' },
    tableTh: { padding: 12, textAlign: 'left', fontWeight: 600, color: '#333' },
    tableRow: { borderBottom: '1px solid #e0e0e0' },
    tableTd: { padding: 12, color: '#333' },
    actionButtonsContainer: { display: 'flex', gap: 12, justifyContent: 'flex-start' },
    editButton: { padding: '10px 24px', background: '#fff', border: '2px solid #00bcd4', color: '#00bcd4', borderRadius: 6, cursor: 'pointer', fontWeight: 600, fontSize: 14 },
    updateButton: { padding: '10px 24px', background: '#0a66ff', border: 'none', color: '#fff', borderRadius: 6, cursor: 'pointer', fontWeight: 600, fontSize: 14 },
    formGrid3: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, marginBottom: 24, padding: 20, background: '#f9f9f9', borderRadius: 8 },
    formLabel: { display: 'block', marginBottom: 8, fontWeight: 500, color: '#333', fontSize: 14 },
    formInput: { width: '100%', padding: '10px 12px', border: '1px solid #ddd', borderRadius: 6, fontSize: 14, boxSizing: 'border-box', fontFamily: 'inherit' },
    inputWithButton: { display: 'flex', gap: 8, alignItems: 'center' },
    formSelect: { padding: '10px 12px', border: '1px solid #ddd', borderRadius: 6, fontSize: 14, flex: 1, fontFamily: 'inherit' },
    addEntryButton: { width: 36, height: 36, borderRadius: '50%', background: '#0a66ff', border: 'none', color: '#fff', cursor: 'pointer', fontSize: 18, fontWeight: 'bold', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    marginBottom24: { marginBottom: 24 },
    currentEntriesTitle: { marginBottom: 12, color: '#333' },
    tableThCenter: { padding: 12, textAlign: 'center', fontWeight: 600, color: '#333' },
    tableTdCenter: { padding: 12, textAlign: 'center' },
    editTableButton: { padding: '6px 12px', background: '#fff', border: '1px solid #0a66ff', color: '#0a66ff', borderRadius: 4, cursor: 'pointer', marginRight: 8, fontSize: 12, fontWeight: 500 },
    deleteTableButton: { padding: '6px 12px', background: '#fff', border: '1px solid #f44336', color: '#f44336', borderRadius: 4, cursor: 'pointer', fontSize: 12, fontWeight: 500 },
    actionButtonsContainerCenter: { display: 'flex', gap: 12, justifyContent: 'center' },
    cancelButton: { padding: '12px 32px', background: '#fff', border: '1px solid #ddd', color: '#333', borderRadius: 6, cursor: 'pointer', fontWeight: 600, fontSize: 14 },
    presCancelButton: {
        background: '#fff',
        color: '#0070f3',
        borderRadius: 6,
        border: '1px solid #0070f3',
        padding: '8px 12px',
        minWidth: '80px',
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 500,
        cursor: 'pointer',
    },
    updateButtonLarge: { padding: '12px 32px', background: '#0a66ff', border: 'none', color: '#fff', borderRadius: 6, fontWeight: 600, fontSize: 14 },
    presEditButton: { padding: '8px 12px', minWidth: '80px', textAlign: 'center', background: '#fff', border: '1px solid #0a66ff', color: '#0a66ff', borderRadius: 6, cursor: 'pointer', marginRight: 8, fontSize: 14, fontWeight: 500 },
    marginTop140: { marginTop: 140 },
    prescriptionTable: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed', minWidth: 900 },
    tableCellPadding: { padding: '8px' },
    inputWithButtonSmall: { display: 'flex', gap: 6 },
    tableInput: { width: '100%', padding: '8px', boxSizing: 'border-box' },
    micButton: { height: 24, width: 24, marginTop: 12 },
    tableSelect: { width: '100%', padding: '8px', boxSizing: 'border-box' },
    tableCellAction: { padding: '8px', verticalAlign: 'middle', width: 200 },
    tableCellViewSmall: { width: 44 },
    tableCellViewMid: { width: 100 },
    tableCellViewNormal: { width: 160 },
    cancelEditButton: { background: '#fff', color: '#0070f3', borderRadius: 6, border: '1px solid #0070f3', padding: '8px 14px' },
    addButton: { background: '#0070f3', color: '#fff', borderRadius: 6, padding: '8px 12px', minWidth: '80px', textAlign: 'center', border: '1px solid #0070f3', cursor: 'pointer', fontSize: 14, fontWeight: 500 },
    marginTop24: { marginTop: 24 },
    meetingProcessControls: { display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' },
    smallLabel: { display: 'block', fontSize: 13, marginBottom: 6 },
    smallInput: { padding: '8px 10px', borderRadius: 6, border: '1px solid #ccc' },
    smallSelect: { padding: '8px 10px', borderRadius: 6, border: '1px solid #ccc' },
    meetingProcessActions: { display: 'flex', alignItems: 'flex-end', gap: 8 },
    processButton: { color: '#fff', padding: '10px 18px', borderRadius: 6, border: 'none' },
    resetButton: { background: '#fff', border: '1px solid #dfe7ff', padding: '10px 14px', borderRadius: 6, cursor: 'pointer' },
    errorText: { color: '#b00020', marginTop: 12 },
    subSectionTitle: { color: '#1976d2', marginBottom: 8 },
    list: { paddingLeft: 20 },
    listItem: { marginBottom: 8 },
    summaryTable: { width: '100%', borderCollapse: 'collapse', marginBottom: 12 },
    summaryTableHeader: { background: '#f5f5f5' },
    summaryTableTh: { padding: 8, border: '1px solid #e0e0e0' },
    summaryTableTd: { padding: 8, border: '1px solid #e0e0e0' },
    marginBottom4: { marginBottom: 4 },
    noDataFound: { marginTop: 24, color: '#888', textAlign: 'center', fontSize: '1.1rem', padding: '40px 0' },
    diagnosticSection: { padding: 24, position: 'relative' },
    diagnosticTitle: { color: '#1e73ff', marginBottom: 12 },
    searchContainer: { display: 'flex', gap: 16, alignItems: 'center', marginBottom: 20 },
    searchInput: { flex: 1, borderRadius: 24, padding: '12px 18px', border: '1px solid #d7e3ff', outline: 'none' },
    diagnosticContent: { display: 'flex', gap: 24, alignItems: 'flex-start' },
    investigationFormCard: { background: '#fff', padding: 16, borderRadius: 8, border: '1px solid #e6eefc', marginBottom: 12 },
    marginTop0: { marginTop: 0 },
    formGrid1: { display: 'grid', gridTemplateColumns: '1fr', gap: 12 },
    textarea: { width: '98%', padding: '8px 10px', borderRadius: 6, border: '1px solid #ddd', resize: 'vertical' },
    formActions: { display: 'flex', gap: 8, justifyContent: 'flex-end' },
    resetButtonSmall: { background: '#fff', border: '1px solid #f0f0f0', padding: '8px 12px', borderRadius: 6, cursor: 'pointer' },
    saveButtonSmall: { background: '#0a66ff', color: '#fff', padding: '8px 12px', borderRadius: 6, border: 'none', cursor: 'pointer' },
    pMuted: { color: '#666', lineHeight: 1.6 },
    imageUploaderContainer: { width: 220 },
    imageUploaderWrapper: { display: 'flex', flexDirection: 'column', gap: 12 },
    imagePreviewArea: { borderRadius: 8, padding: 12, display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 140, background: '#fff', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' },
    imagePreview: { maxWidth: '100%', maxHeight: 160, borderRadius: 6 },
    imageDropText: { color: '#9aaae6' },
    thumbnailContainer: { display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' },
    thumbnail: { width: 120, borderRadius: 8, background: '#fff', boxShadow: '0 2px 6px rgba(0,0,0,0.06)', overflow: 'hidden' },
    thumbnailImg: { width: '100%', height: 80, objectFit: 'cover' },
    thumbnailActions: { padding: 8, display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
    thumbnailDate: { fontSize: 12, color: '#777' },
    thumbnailButtons: { display: 'flex', gap: 8 },
    editIconButton: { border: 'none', background: 'transparent', cursor: 'pointer', color: '#1e73ff' },
    deleteIconButton: { border: 'none', background: 'transparent', cursor: 'pointer', color: '#ff4d4f' },
    imageUploaderControls: { display: 'flex', left: 10, gap: 10, alignItems: 'center' },
    uploadButton: { border: '1px dashed #cfe0ff', padding: '8px 5px', borderRadius: 8, cursor: 'pointer' },
    removeAllButton: { background: '#fff', border: '1px solid #f0f0f0', padding: '8px 12px', borderRadius: 8, cursor: 'pointer' },
    marginTop20: { marginTop: 20 },
    investigationListTitle: { marginTop: 8, marginBottom: 12, color: '#1e73ff' },
    investigationList: { display: 'flex', flexDirection: 'column', gap: 12 },
    investigationItem: { display: 'flex', gap: 12, alignItems: 'flex-start', padding: 12, border: '1px solid #e0e0e0', borderRadius: 8, background: '#fff' },
    investigationItemTitle: { fontWeight: 700, color: '#111', fontSize: 15 },
    investigationItemDescription: { color: '#666', marginTop: 6 },
    investigationItemDate: { marginTop: 8, color: '#444', fontSize: 13 },
    investigationItemImageContainer: { width: 160, textAlign: 'right' },
    investigationItemImage: { width: 140, height: 110, objectFit: 'contain', borderRadius: 6, border: '1px solid #f0f0f0' },
    noFileText: { color: '#999' },
    datePickerContainer: { marginBottom: 24, display: 'flex', gap: 12, alignItems: 'flex-end' },
    datePickerWrapper: { flex: 1, maxWidth: 300 },
    loadingText: { padding: 12, background: '#e3f2fd', borderRadius: 6, color: '#1976d2', marginBottom: 20 },
    noDataContainer: { padding: 40, textAlign: 'center', background: '#f5f5f5', borderRadius: 8, marginBottom: 20 },
    symptomsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 24 },
    marginBottom20: { marginBottom: 20 },
    symptomLabel: { display: 'block', fontWeight: 600, color: '#333', marginBottom: 4, fontSize: 14 },
    symptomValue: { margin: 0, padding: '10px 0', color: '#666', lineHeight: 1.6 },
    centerContent: { alignContent: 'center', justifyContent: 'center' },
    noDataLabel: { textAlign: 'center', color: '#555', fontStyle: 'italic', width: '100%', display: 'block', marginTop: 20 },
    prescriptionTableWrapper: {
        maxHeight: '400px', // Set a max height for scrolling
        overflowY: 'auto', // Enable vertical scrolling
        border: '1px solid #e0e0e0', // Optional: add a border to the scrolling area
        borderRadius: 8,
        marginBottom: 20,
        background: '#fff',
    },
    stickyTableHeader: { position: 'sticky', top: 0, backgroundColor: '#f5f5f5', zIndex: 1, padding: '12px', textAlign: 'left', fontWeight: 600, color: '#333' },
    addPrescriptionButton: { background: '#0070f3', color: '#fff', borderRadius: 6, padding: '8px 14px', border: 'none', cursor: 'pointer' },
    removeTableButton: { background: '#fff', color: '#f44336', borderRadius: 6, padding: '8px 12px', minWidth: '80px', textAlign: 'center', border: '1px solid #f44336', cursor: 'pointer', fontSize: 14, fontWeight: 500 },
    updatePrescriptionButton: {
        borderRadius: 6,
        color: '#fff',
        padding: '8px 12px',
        minWidth: '80px',
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 500,
    },
};
